export const ASAAS_PAYMENT_EVENTS = {
  PAYMENT_CREATED: 'PAYMENT_CREATED',
  PAYMENT_UPDATED: 'PAYMENT_UPDATED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_RECEIVED_IN_CASH: 'PAYMENT_RECEIVED_IN_CASH',
  PAYMENT_OVERDUE: 'PAYMENT_OVERDUE',
  PAYMENT_REFUND_IN_PROGRESS: 'PAYMENT_REFUND_IN_PROGRESS',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_DELETED: 'PAYMENT_DELETED',
};
